name: cosdart
description: Contentos blockchain SDK for Dart.
version: 0.2.2
homepage: https://github.com/coschain/cosdart

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  protobuf: 2.1.0
  grpc: ^3.1.0
  fixnum: ^1.1.0
  crclib: ^3.0.0

dev_dependencies:
  test: ^1.11.0
